<script setup lang="ts">
import Note from "./Note.vue";


</script>

<template>
<div id="new-button">
    +
</div>
<section id="notes-list">
    <Note :idNum="1" noteTitle="title" content="hello"/>
    <Note :idNum="2" noteTitle="title" content="helloasdkjfhaskldhfkjadshkfhasdhhelloasdkjfhaskldhfkjadshkfhasdhfashjdfhlasdhjfhasdhfkjashdfhashdkfhaskjdhfkahsdjkfhaksldhfkjhsdkjfhjkahsdkjfhakjlshdflkhasdjkhfldksjhelloasdkjfhaskldhfkjadshkfhasdhfashjdfhlasdhjfhasdhfkjashdfhashdkfhaskjdhfkahsdjkfhaksldhfkjhsdkjfhjkahsdkjfhakjlshdflkhasdjkhfldksjhelloasdkjfhaskldhfkjadshkfhasdhfashjdfhlasdhjfhasdhfkjashdfhashdkfhaskjdhfkahsdjkfhaksldhfkjhsdkjfhjkahsdkjfhakjlshdflkhasdjkhfldksjhelloasdkjfhaskldhfkjadshkfhasdhfashjdfhlasdhjfhasdhfkjashdfhashdkfhaskjdhfkahsdjkfhaksldhfkjhsdkjfhjkahsdkjfhakjlshdflkhasdjkhfldksjhelloasdkjfhaskldhfkjadshkfhasdhfashjdfhlasdhjfhasdhfkjashdfhashdkfhaskjdhfkahsdjkfhaksldhfkjhsdkjfhjkahsdkjfhakjlshdflkhasdjkhfldksjhelloasdkjfhaskldhfkjadshkfhasdhfashjdfhlasdhjfhasdhfkjashdfhashdkfhaskjdhfkahsdjkfhaksldhfkjhsdkjfhjkahsdkjfhakjlshdflkhasdjkhfldksjhelloasdkjfhaskldhfkjadshkfhasdhfashjdfhlasdhjfhasdhfkjashdfhashdkfhaskjdhfkahsdjkfhaksldhfkjhsdkjfhjkahsdkjfhakjlshdflkhasdjkhfldksjhelloasdkjfhaskldhfkjadshkfhasdhfashjdfhlasdhjfhasdhfkjashdfhashdkfhaskjdhfkahsdjkfhaksldhfkjhsdkjfhjkahsdkjfhakjlshdflkhasdjkhfldksjhelloasdkjfhaskldhfkjadshkfhasdhfashjdfhlasdhjfhasdhfkjashdfhashdkfhaskjdhfkahsdjkfhaksldhfkjhsdkjfhjkahsdkjfhakjlshdflkhasdjkhfldksjhelloasdkjfhaskldhfkjadshkfhasdhfashjdfhlasdhjfhasdhfkjashdfhashdkfhaskjdhfkahsdjkfhaksldhfkjhsdkjfhjkahsdkjfhakjlshdflkhasdjkhfldksjfashjdfhlasdhjfhasdhfkjashdfhashdkfhaskjdhfkahsdjkfhaksldhfkjhsdkjfhjkahsdkjfhakjlshdflkhasdjkhfldksj"/>
    <Note :idNum="3" noteTitle="title" content="hello"/>
    <Note :idNum="4" noteTitle="title" content="hello"/>
</section>
</template>